# Nylo - Micro-framework for Flutter.
#
# Website: https://nylo.dev
# Official repository: https://github.com/nylo-core/nylo
# Author: Anthony Gordon <https://github.com/agordn52>

name: flutter_app
description: A new Nylo Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=3.24.0 <4.0.0"
dependencies:
  url_launcher: ^6.3.2
  google_fonts: ^6.3.2
  analyzer: ^9.0.0
  intl: ^0.20.2
  nylo_framework: ^6.9.1
  pretty_dio_logger: ^1.4.0
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.5
  flutter_local_notifications: ^19.5.0
  font_awesome_flutter: ^10.12.0
  scaffold_ui: ^1.2.9
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  geolocator: ^14.0.2
  sqflite: ^2.4.2
  path: ^1.9.1
  flutter_svg: ^2.2.3
  image_picker: ^1.2.1
  sqlite3_flutter_libs: ^0.5.41

dev_dependencies:
  rename: ^3.1.0
  flutter_launcher_icons: ^0.14.4
  # The following line 'flutter_lints' activates a set of recommended lints for Flutter apps,
  # packages, and plugins designed to encourage good coding practices.
#  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

# APP ICON - public/app_icon/logo.png
# Build icons: "dart run flutter_launcher_icons"
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "public/app_icon/logo.png"
  remove_alpha_ios: true

# RENAME YOUR PROJECT
# flutter pub run rename setAppName --targets ios,android --value "YourAppName"

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - public/fonts/
    - public/images/
    - public/app_icon/
    - lang/
    - .env
    - assets/data/disasters_type.json